In [1]:
!pip install tensorflow==2.2

     |████████████████████████████████| 516.2MB 34kB/s 
     |████████████████████████████████| 3.0MB 28.2MB/s 
     |████████████████████████████████| 460kB 51.9MB/s 
  Found existing installation: tensorboard 2.4.1
    Uninstalling tensorboard-2.4.1:
      Successfully uninstalled tensorboard-2.4.1
  Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Found existing installation: tensorflow 2.4.1
    Uninstalling tensorflow-2.4.1:
      Successfully uninstalled tensorflow-2.4.1


In [2]:
import tensorflow as tf
tf.__version__

'2.2.0'

In [3]:
!pip install keras

In [4]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [5]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist
(train_x,train_y), (test_x, test_y) = mnist.load_data()
train_x, test_x = train_x/255.0, test_x/255.0
epochs=10

11493376/11490434 [==============================] - 0s 0us/step


In [6]:
train_y

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
train_x

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [16]:
#batch_size=32
#epochs=10

In [13]:
train_x , test_x = tf.cast(train_x/255.0,tf.float32), tf.cast(test_x/255.0,tf.float32)
train_y , test_y = tf.cast(train_y,tf.int32), tf.cast(test_y,tf.int32)

In [8]:
#Now in the fit() function, we can pass the dataset directly in, as follows:
model5 = tf.keras.models.Sequential([
 tf.keras.layers.Flatten(),
 tf.keras.layers.Dense(512,activation=tf.nn.relu),
 tf.keras.layers.Dropout(0.2),
 tf.keras.layers.Dense(10,activation=tf.nn.softmax)
])

In [14]:

optimiser = tf.keras.optimizers.Adam()
model5.compile (optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

In [17]:
model5.fit(train_x,train_y, batch_size=32, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.8910 - accuracy: 0.7760
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3902 - accuracy: 0.8894
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3308 - accuracy: 0.9045
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2992 - accuracy: 0.9132
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2752 - accuracy: 0.9194


In [18]:
model5.evaluate(test_x,test_y)

313/313 [==============================] - 1s 2ms/step - loss: 0.2532 - accuracy: 0.9249


[0.25317612290382385, 0.9248999953269958]

In [19]:
model5.predict(test_x)

array([[7.08268781e-05, 1.86517148e-08, 8.46688999e-05, ...,
        9.97090936e-01, 1.01755350e-05, 9.48334404e-04],
       [2.19778134e-03, 4.33668429e-05, 9.65289831e-01, ...,
        1.89793389e-10, 1.49292359e-03, 3.57511931e-09],
       [1.94751578e-06, 9.84520257e-01, 5.51983807e-03, ...,
        3.55010992e-03, 1.42817223e-03, 4.54617955e-04],
       ...,
       [3.74436780e-07, 2.59085550e-06, 3.03595643e-05, ...,
        1.54575810e-03, 7.10113533e-03, 6.68879226e-02],
       [6.54316740e-04, 1.84593169e-04, 3.43429383e-05, ...,
        5.21629408e-06, 1.24276228e-01, 4.09340464e-05],
       [1.12465386e-04, 2.28404795e-10, 2.11668666e-04, ...,
        7.80700837e-10, 5.54178484e-07, 1.43406751e-07]], dtype=float32)

In [32]:
model2=tf.keras.models.Sequential()
model2.add(tf.keras.layers.Flatten())
model2.add(tf.keras.layers.Dense(512,activation=tf.nn.relu))
model2.add(tf.keras.layers.Dropout(0.2))
model2.add(tf.keras.layers.Dense(10,activation=tf.nn.softmax))

model2.compile(optimizer=optimiser,loss='sparse_categorical_crossentropy', metrics= ['accuracy'])

In [33]:
model2.fit(train_x,train_y,epochs=5,batch_size=64)

Epoch 1/5
938/938 [==============================] - 5s 6ms/step - loss: 0.7048 - accuracy: 0.8110
Epoch 2/5
938/938 [==============================] - 5s 6ms/step - loss: 0.3897 - accuracy: 0.8902
Epoch 3/5
938/938 [==============================] - 5s 6ms/step - loss: 0.3421 - accuracy: 0.9011
Epoch 4/5
938/938 [==============================] - 5s 6ms/step - loss: 0.3173 - accuracy: 0.9079
Epoch 5/5
938/938 [==============================] - 5s 6ms/step - loss: 0.2973 - accuracy: 0.9130


In [34]:
model2.evaluate(test_x,test_y)

313/313 [==============================] - 1s 2ms/step - loss: 0.2707 - accuracy: 0.9196


[0.2706713080406189, 0.9196000099182129]

In [36]:
tf.saved_model.save(model2, export_dir="F:/ineuron data/Deap Learning/DLCV/MyProjects/NeuralNetworkModelFile")

INFO:tensorflow:Assets written to: F:/ineuron data/Deap Learning/DLCV/MyProjects/NeuralNetworkModelFile/assets


In [37]:
tf.saved_model.save(model5, export_dir="F:/ineuron data/Deap Learning/DLCV/MyProjects/NeuralNetworkModelFile")

INFO:tensorflow:Assets written to: F:/ineuron data/Deap Learning/DLCV/MyProjects/NeuralNetworkModelFile/assets
